version: "3.8"

services:
  app:
    container_name: polyglotter-api
    build: .
    env_file:
      - ./docker/${ENV}.env
    ports:
      - "3000:3000"
    depends_on:
      - db
    restart: unless-stopped
    volumes:
      - .:/app

  db:
    image: postgres:15
    container_name: polyglotter-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: polyglotter
    volumes:
      - /mnt/postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
