version: "3.8"

services:
  db:
    image: postgres:16
    container_name: polyglotter-db
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app-network

  app:
    build: .
    container_name: polyglotter-app
    restart: always
    depends_on:
      - db
    env_file:
      - .env
    ports:
      - "3001:3000"
    networks:
      - app-network
    command: sh -c "yarn build && npx prisma migrate deploy && node dist/index.js"

volumes:
  pgdata:

networks:
  app-network:
