name: Deploy to PROD

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: prod

    steps:
      - uses: actions/checkout@v3

      - name: Connect to Tailscale
        uses: tailscale/github-action@v1
        with:
          authkey: ${{ secrets.TAILSCALE_AUTHKEY }}

      - name: Rsync code to Raspberry Pi (PROD)
        run: |
          rsync -avz --delete \
            -e "ssh -o StrictHostKeyChecking=no" \
            ./ raspberrypi.tailf42ca6.ts.net:~/polyglotter-api

      - name: Deploy to PROD
        run: |
          ssh raspberrypi.tailf42ca6.ts.net <<'EOF'
            cd ~/polyglotter-api
            echo "${{ secrets.POSTGRES_PASSWORD }}" > docker/prod.env
            ENV=${{ vars.ENV }} docker compose down
            ENV=${{ vars.ENV }} docker compose up -d --build
          EOF
