name: Run Migrations on Dev

on:
  workflow_dispatch:

env:
  ENVIRONMENT_NAME: dev

jobs:
  migrate:
    runs-on: ubuntu-latest
    environment: dev

    steps:
    - uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Run Prisma Migrations
      run: |
        ssh -o StrictHostKeyChecking=no root@49.12.75.106 << 'EOF'
          cd /root/polyglotter-api-dev
          docker compose exec app npx prisma migrate deploy
        EOF
